import type {
  BreadcrumbItem,
  NavigationEntry,
  NavigationSource,
} from "../types";

const staticEntries: NavigationEntry[] = [
  {
    key: "private-dashboard",
    label: "Dashboard",
    href: "/dashboard",
    context: "private",
    slot: "main",
    section: "Portal",
    icon: { name: "dashboard" },
    exact: true,
    order: 10,
    sitemap: false,
  },
  {
    key: "private-profile",
    label: "Perfil",
    href: "/profile",
    context: "private",
    slot: "main",
    section: "Portal",
    icon: { name: "user" },
    order: 20,
    sitemap: false,
  },
  {
    key: "private-account",
    label: "Conta",
    href: "/account",
    context: "private",
    slot: "main",
    section: "Portal",
    icon: { name: "settings" },
    order: 30,
    sitemap: false,
  },
  {
    key: "private-notifications",
    label: "Notificações",
    href: "/notifications",
    context: "private",
    slot: "main",
    section: "Portal",
    icon: { name: "bell" },
    order: 40,
    sitemap: false,
  },

  {
    key: "private-account-overview",
    label: "Visão geral",
    href: "/account",
    context: "private",
    slot: "context",
    section: "Conta",
    icon: { name: "settings" },
    match: "/account",
    order: 10,
    sitemap: false,
  },

  {
    key: "user-profile",
    label: "Meu perfil",
    href: "/profile",
    context: "private",
    slot: "user",
    icon: { name: "user" },
    order: 10,
    sitemap: false,
  },
  {
    key: "user-account",
    label: "Minha conta",
    href: "/account",
    context: "private",
    slot: "user",
    icon: { name: "settings" },
    order: 20,
    sitemap: false,
  },
  {
    key: "user-logout",
    label: "Sair",
    href: "/logout",
    context: "private",
    slot: "user",
    icon: { name: "log-out" },
    danger: true,
    order: 999,
    sitemap: false,
  },

  {
    key: "admin-dashboard",
    label: "Dashboard",
    href: "/admin",
    context: "admin",
    slot: "main",
    section: "Administração",
    icon: { name: "home" },
    exact: true,
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-users",
    label: "Usuários",
    href: "/admin/users",
    context: "admin",
    slot: "main",
    section: "Acesso",
    icon: { name: "users" },
    permission: "users.manage",
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-roles",
    label: "Papéis e permissões",
    href: "/admin/roles",
    context: "admin",
    slot: "main",
    section: "Acesso",
    icon: { name: "shield" },
    permission: "roles.manage",
    order: 20,
    sitemap: false,
  },
  {
    key: "admin-pages",
    label: "Páginas",
    href: "/admin/pages",
    context: "admin",
    slot: "main",
    section: "CMS",
    icon: { name: "file-text" },
    permission: "pages.manage",
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-menus",
    label: "Menus",
    href: "/admin/menus",
    context: "admin",
    slot: "main",
    section: "CMS",
    icon: { name: "menu-square" },
    permission: "menus.manage",
    order: 20,
    sitemap: false,
  },
  {
    key: "admin-media",
    label: "Mídia",
    href: "/admin/media",
    context: "admin",
    slot: "main",
    section: "CMS",
    icon: { name: "image" },
    permission: "media.manage",
    order: 30,
    sitemap: false,
  },
  {
    key: "admin-modules",
    label: "Módulos",
    href: "/admin/modules",
    context: "admin",
    slot: "main",
    section: "Sistema",
    icon: { name: "blocks" },
    permission: "modules.manage",
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-settings",
    label: "Configurações",
    href: "/admin/settings",
    context: "admin",
    slot: "main",
    section: "Sistema",
    icon: { name: "settings" },
    permission: "settings.manage",
    order: 20,
    sitemap: false,
  },

  {
    key: "admin-users-list",
    label: "Todos os usuários",
    href: "/admin/users",
    context: "admin",
    slot: "context",
    section: "Usuários",
    icon: { name: "users" },
    permission: "users.manage",
    match: "/admin/users",
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-users-create",
    label: "Novo usuário",
    href: "/admin/users/create",
    context: "admin",
    slot: "context",
    section: "Usuários",
    icon: { name: "plus" },
    permission: "users.manage",
    match: "/admin/users",
    order: 20,
    sitemap: false,
  },
  {
    key: "admin-roles-list",
    label: "Papéis",
    href: "/admin/roles",
    context: "admin",
    slot: "context",
    section: "Permissões",
    icon: { name: "shield" },
    permission: "roles.manage",
    match: "/admin/roles",
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-pages-list",
    label: "Todas as páginas",
    href: "/admin/pages",
    context: "admin",
    slot: "context",
    section: "Páginas",
    icon: { name: "list" },
    permission: "pages.manage",
    match: "/admin/pages",
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-pages-create",
    label: "Nova página",
    href: "/admin/pages/create",
    context: "admin",
    slot: "context",
    section: "Páginas",
    icon: { name: "plus" },
    permission: "pages.manage",
    match: "/admin/pages",
    order: 20,
    sitemap: false,
  },

  {
    key: "admin-profile",
    label: "Meu perfil",
    href: "/profile",
    context: "admin",
    slot: "user",
    icon: { name: "user" },
    order: 10,
    sitemap: false,
  },
  {
    key: "admin-account",
    label: "Minha conta",
    href: "/account",
    context: "admin",
    slot: "user",
    icon: { name: "settings" },
    order: 20,
    sitemap: false,
  },
  {
    key: "admin-security",
    label: "Segurança",
    href: "/admin/settings",
    context: "admin",
    slot: "user",
    icon: { name: "shield" },
    permission: "settings.manage",
    order: 30,
    sitemap: false,
  },
  {
    key: "admin-logout",
    label: "Sair",
    href: "/logout",
    context: "admin",
    slot: "user",
    icon: { name: "log-out" },
    danger: true,
    order: 999,
    sitemap: false,
  },
];

const staticBreadcrumbs: Array<{
  pattern: RegExp;
  items: BreadcrumbItem[];
}> = [
  {
    pattern: /^\/admin$/,
    items: [{ key: "admin", label: "Admin", href: "/admin" }],
  },
  {
    pattern: /^\/admin\/users$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      { key: "admin-users", label: "Usuários", href: "/admin/users" },
    ],
  },
  {
    pattern: /^\/admin\/users\/create$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      { key: "admin-users", label: "Usuários", href: "/admin/users" },
      { key: "admin-users-create", label: "Criar usuário" },
    ],
  },
  {
    pattern: /^\/admin\/roles$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      {
        key: "admin-roles",
        label: "Papéis e permissões",
        href: "/admin/roles",
      },
    ],
  },
  {
    pattern: /^\/admin\/pages$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      { key: "admin-pages", label: "Páginas", href: "/admin/pages" },
    ],
  },
  {
    pattern: /^\/admin\/pages\/create$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      { key: "admin-pages", label: "Páginas", href: "/admin/pages" },
      { key: "admin-pages-create", label: "Nova página" },
    ],
  },
  {
    pattern: /^\/admin\/menus$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      { key: "admin-menus", label: "Menus", href: "/admin/menus" },
    ],
  },
  {
    pattern: /^\/admin\/media$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      { key: "admin-media", label: "Mídia", href: "/admin/media" },
    ],
  },
  {
    pattern: /^\/admin\/modules$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      { key: "admin-modules", label: "Módulos", href: "/admin/modules" },
    ],
  },
  {
    pattern: /^\/admin\/settings$/,
    items: [
      { key: "admin", label: "Admin", href: "/admin" },
      {
        key: "admin-settings",
        label: "Configurações",
        href: "/admin/settings",
      },
    ],
  },
  {
    pattern: /^\/dashboard$/,
    items: [
      { key: "private-dashboard", label: "Dashboard", href: "/dashboard" },
    ],
  },
  {
    pattern: /^\/profile$/,
    items: [{ key: "private-profile", label: "Perfil", href: "/profile" }],
  },
  {
    pattern: /^\/account$/,
    items: [{ key: "private-account", label: "Conta", href: "/account" }],
  },
  {
    pattern: /^\/notifications$/,
    items: [
      {
        key: "private-notifications",
        label: "Notificações",
        href: "/notifications",
      },
    ],
  },
];

export const staticNavigationSource: NavigationSource = {
  getEntries() {
    return staticEntries;
  },

  getBreadcrumbs(pathname: string) {
    const match = staticBreadcrumbs.find((item) => item.pattern.test(pathname));
    return match?.items ?? [];
  },
};
